name: BWP
version: '${project.version}'
main: me.trixxtraxx.Practice.Practice
api-version: 1.18
authors: [ TrixxTraxx ]
description: Bedwars Practice core
website: store.ranked.fun
depend:
  - InventoryAPI

commands:
  TestGame:
  leave:
  kit:
  InventoryView:
  OpenGUI:
  DuelSettings:
  Spectate: